# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_analysis.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai_analysis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61i_analysis.proto\x12\x0b\x61i_analysis\"9\n\x12LogAnalysisRequest\x12#\n\x04logs\x18\x01 \x03(\x0b\x32\x15.ai_analysis.LogEntry\"\xc1\x01\n\x08LogEntry\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t\x12\r\n\x05level\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x0e\n\x06source\x18\x05 \x01(\t\x12\x35\n\x08metadata\x18\x06 \x03(\x0b\x32#.ai_analysis.LogEntry.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"j\n\x13LogAnalysisResponse\x12,\n\x07results\x18\x01 \x03(\x0b\x32\x1b.ai_analysis.AnalysisResult\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t\"y\n\x0e\x41nalysisResult\x12\x0e\n\x06log_id\x18\x01 \x01(\t\x12\x12\n\nis_anomaly\x18\x02 \x01(\x08\x12\x15\n\ranomaly_score\x18\x03 \x01(\x01\x12\x13\n\x0broot_causes\x18\x04 \x03(\t\x12\x17\n\x0frecommendations\x18\x05 \x03(\t2e\n\x11\x41IAnalysisService\x12P\n\x0b\x41nalyzeLogs\x12\x1f.ai_analysis.LogAnalysisRequest\x1a .ai_analysis.LogAnalysisResponseB$Z\"intelligent-log-analysis/pkg/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_analysis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\"intelligent-log-analysis/pkg/proto'
  _globals['_LOGENTRY_METADATAENTRY']._loaded_options = None
  _globals['_LOGENTRY_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_LOGANALYSISREQUEST']._serialized_start=34
  _globals['_LOGANALYSISREQUEST']._serialized_end=91
  _globals['_LOGENTRY']._serialized_start=94
  _globals['_LOGENTRY']._serialized_end=287
  _globals['_LOGENTRY_METADATAENTRY']._serialized_start=240
  _globals['_LOGENTRY_METADATAENTRY']._serialized_end=287
  _globals['_LOGANALYSISRESPONSE']._serialized_start=289
  _globals['_LOGANALYSISRESPONSE']._serialized_end=395
  _globals['_ANALYSISRESULT']._serialized_start=397
  _globals['_ANALYSISRESULT']._serialized_end=518
  _globals['_AIANALYSISSERVICE']._serialized_start=520
  _globals['_AIANALYSISSERVICE']._serialized_end=621
# @@protoc_insertion_point(module_scope)
