// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: pkg/proto/ai_analysis.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIAnalysisService_AnalyzeLogs_FullMethodName = "/ai_analysis.AIAnalysisService/AnalyzeLogs"
)

// AIAnalysisServiceClient is the client API for AIAnalysisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIAnalysisServiceClient interface {
	AnalyzeLogs(ctx context.Context, in *LogAnalysisRequest, opts ...grpc.CallOption) (*LogAnalysisResponse, error)
}

type aIAnalysisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIAnalysisServiceClient(cc grpc.ClientConnInterface) AIAnalysisServiceClient {
	return &aIAnalysisServiceClient{cc}
}

func (c *aIAnalysisServiceClient) AnalyzeLogs(ctx context.Context, in *LogAnalysisRequest, opts ...grpc.CallOption) (*LogAnalysisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogAnalysisResponse)
	err := c.cc.Invoke(ctx, AIAnalysisService_AnalyzeLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIAnalysisServiceServer is the server API for AIAnalysisService service.
// All implementations must embed UnimplementedAIAnalysisServiceServer
// for forward compatibility.
type AIAnalysisServiceServer interface {
	AnalyzeLogs(context.Context, *LogAnalysisRequest) (*LogAnalysisResponse, error)
	mustEmbedUnimplementedAIAnalysisServiceServer()
}

// UnimplementedAIAnalysisServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIAnalysisServiceServer struct{}

func (UnimplementedAIAnalysisServiceServer) AnalyzeLogs(context.Context, *LogAnalysisRequest) (*LogAnalysisResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeLogs not implemented")
}
func (UnimplementedAIAnalysisServiceServer) mustEmbedUnimplementedAIAnalysisServiceServer() {}
func (UnimplementedAIAnalysisServiceServer) testEmbeddedByValue()                           {}

// UnsafeAIAnalysisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIAnalysisServiceServer will
// result in compilation errors.
type UnsafeAIAnalysisServiceServer interface {
	mustEmbedUnimplementedAIAnalysisServiceServer()
}

func RegisterAIAnalysisServiceServer(s grpc.ServiceRegistrar, srv AIAnalysisServiceServer) {
	// If the following call panics, it indicates UnimplementedAIAnalysisServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIAnalysisService_ServiceDesc, srv)
}

func _AIAnalysisService_AnalyzeLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogAnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIAnalysisServiceServer).AnalyzeLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIAnalysisService_AnalyzeLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIAnalysisServiceServer).AnalyzeLogs(ctx, req.(*LogAnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIAnalysisService_ServiceDesc is the grpc.ServiceDesc for AIAnalysisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIAnalysisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai_analysis.AIAnalysisService",
	HandlerType: (*AIAnalysisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeLogs",
			Handler:    _AIAnalysisService_AnalyzeLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/ai_analysis.proto",
}
