// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/proto/ai_analysis.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogAnalysisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*LogEntry            `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogAnalysisRequest) Reset() {
	*x = LogAnalysisRequest{}
	mi := &file_pkg_proto_ai_analysis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogAnalysisRequest) ProtoMessage() {}

func (x *LogAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ai_analysis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogAnalysisRequest.ProtoReflect.Descriptor instead.
func (*LogAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ai_analysis_proto_rawDescGZIP(), []int{0}
}

func (x *LogAnalysisRequest) GetLogs() []*LogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_pkg_proto_ai_analysis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ai_analysis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ai_analysis_proto_rawDescGZIP(), []int{1}
}

func (x *LogEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LogEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogEntry) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type LogAnalysisResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*AnalysisResult      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogAnalysisResponse) Reset() {
	*x = LogAnalysisResponse{}
	mi := &file_pkg_proto_ai_analysis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogAnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogAnalysisResponse) ProtoMessage() {}

func (x *LogAnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ai_analysis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogAnalysisResponse.ProtoReflect.Descriptor instead.
func (*LogAnalysisResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ai_analysis_proto_rawDescGZIP(), []int{2}
}

func (x *LogAnalysisResponse) GetResults() []*AnalysisResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *LogAnalysisResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LogAnalysisResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type AnalysisResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LogId           string                 `protobuf:"bytes,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	IsAnomaly       bool                   `protobuf:"varint,2,opt,name=is_anomaly,json=isAnomaly,proto3" json:"is_anomaly,omitempty"`
	AnomalyScore    float64                `protobuf:"fixed64,3,opt,name=anomaly_score,json=anomalyScore,proto3" json:"anomaly_score,omitempty"`
	RootCauses      []string               `protobuf:"bytes,4,rep,name=root_causes,json=rootCauses,proto3" json:"root_causes,omitempty"`
	Recommendations []string               `protobuf:"bytes,5,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AnalysisResult) Reset() {
	*x = AnalysisResult{}
	mi := &file_pkg_proto_ai_analysis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisResult) ProtoMessage() {}

func (x *AnalysisResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ai_analysis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisResult.ProtoReflect.Descriptor instead.
func (*AnalysisResult) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ai_analysis_proto_rawDescGZIP(), []int{3}
}

func (x *AnalysisResult) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

func (x *AnalysisResult) GetIsAnomaly() bool {
	if x != nil {
		return x.IsAnomaly
	}
	return false
}

func (x *AnalysisResult) GetAnomalyScore() float64 {
	if x != nil {
		return x.AnomalyScore
	}
	return 0
}

func (x *AnalysisResult) GetRootCauses() []string {
	if x != nil {
		return x.RootCauses
	}
	return nil
}

func (x *AnalysisResult) GetRecommendations() []string {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

var File_pkg_proto_ai_analysis_proto protoreflect.FileDescriptor

const file_pkg_proto_ai_analysis_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/proto/ai_analysis.proto\x12\vai_analysis\"?\n" +
	"\x12LogAnalysisRequest\x12)\n" +
	"\x04logs\x18\x01 \x03(\v2\x15.ai_analysis.LogEntryR\x04logs\"\xfe\x01\n" +
	"\bLogEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12?\n" +
	"\bmetadata\x18\x06 \x03(\v2#.ai_analysis.LogEntry.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x89\x01\n" +
	"\x13LogAnalysisResponse\x125\n" +
	"\aresults\x18\x01 \x03(\v2\x1b.ai_analysis.AnalysisResultR\aresults\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xb6\x01\n" +
	"\x0eAnalysisResult\x12\x15\n" +
	"\x06log_id\x18\x01 \x01(\tR\x05logId\x12\x1d\n" +
	"\n" +
	"is_anomaly\x18\x02 \x01(\bR\tisAnomaly\x12#\n" +
	"\ranomaly_score\x18\x03 \x01(\x01R\fanomalyScore\x12\x1f\n" +
	"\vroot_causes\x18\x04 \x03(\tR\n" +
	"rootCauses\x12(\n" +
	"\x0frecommendations\x18\x05 \x03(\tR\x0frecommendations2e\n" +
	"\x11AIAnalysisService\x12P\n" +
	"\vAnalyzeLogs\x12\x1f.ai_analysis.LogAnalysisRequest\x1a .ai_analysis.LogAnalysisResponseB$Z\"intelligent-log-analysis/pkg/protob\x06proto3"

var (
	file_pkg_proto_ai_analysis_proto_rawDescOnce sync.Once
	file_pkg_proto_ai_analysis_proto_rawDescData []byte
)

func file_pkg_proto_ai_analysis_proto_rawDescGZIP() []byte {
	file_pkg_proto_ai_analysis_proto_rawDescOnce.Do(func() {
		file_pkg_proto_ai_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_ai_analysis_proto_rawDesc), len(file_pkg_proto_ai_analysis_proto_rawDesc)))
	})
	return file_pkg_proto_ai_analysis_proto_rawDescData
}

var file_pkg_proto_ai_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_proto_ai_analysis_proto_goTypes = []any{
	(*LogAnalysisRequest)(nil),  // 0: ai_analysis.LogAnalysisRequest
	(*LogEntry)(nil),            // 1: ai_analysis.LogEntry
	(*LogAnalysisResponse)(nil), // 2: ai_analysis.LogAnalysisResponse
	(*AnalysisResult)(nil),      // 3: ai_analysis.AnalysisResult
	nil,                         // 4: ai_analysis.LogEntry.MetadataEntry
}
var file_pkg_proto_ai_analysis_proto_depIdxs = []int32{
	1, // 0: ai_analysis.LogAnalysisRequest.logs:type_name -> ai_analysis.LogEntry
	4, // 1: ai_analysis.LogEntry.metadata:type_name -> ai_analysis.LogEntry.MetadataEntry
	3, // 2: ai_analysis.LogAnalysisResponse.results:type_name -> ai_analysis.AnalysisResult
	0, // 3: ai_analysis.AIAnalysisService.AnalyzeLogs:input_type -> ai_analysis.LogAnalysisRequest
	2, // 4: ai_analysis.AIAnalysisService.AnalyzeLogs:output_type -> ai_analysis.LogAnalysisResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_proto_ai_analysis_proto_init() }
func file_pkg_proto_ai_analysis_proto_init() {
	if File_pkg_proto_ai_analysis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_ai_analysis_proto_rawDesc), len(file_pkg_proto_ai_analysis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_ai_analysis_proto_goTypes,
		DependencyIndexes: file_pkg_proto_ai_analysis_proto_depIdxs,
		MessageInfos:      file_pkg_proto_ai_analysis_proto_msgTypes,
	}.Build()
	File_pkg_proto_ai_analysis_proto = out.File
	file_pkg_proto_ai_analysis_proto_goTypes = nil
	file_pkg_proto_ai_analysis_proto_depIdxs = nil
}
